// Controllers/plantCultivation/phenologyController.js

const SeedBatch = require("../../Model/plantCultivation/SeedBatchModel");
const Crop = require("../../Model/plantCultivation/CropModel"); // baseline (name, baseTemp, stageGDD)
const ClimateDaily = require("../../Model/plantCultivation/ClimateDailyModel");
const PhenologyState = require("../../Model/plantCultivation/PhenologyStateModel");
const PlantingPlan = require("../../Model/plantCultivation/PlantingPlanModel");
const Task = require("../../Model/plantCultivation/CultivationTaskModel");

/* ------------------------ helpers ------------------------ */

const onlyDate = (d) => new Date(d.getFullYear(), d.getMonth(), d.getDate());
const meanTemp = (tmin, tmax) => (tmin + tmax) / 2;

/**
 * Resolve crop name for a plan (cache aware).
 * Prefer plan.seedBatchId -> SeedBatch.cropType/crop,
 * fall back to plan.cropType or plan.crop (or variety).
 */
async function resolveCropName(plan, cache = {}) {
  if (!plan) return null;

  if (plan.seedBatchId) {
    const key = String(plan.seedBatchId);
    if (cache[key] === undefined) {
      const sb = await SeedBatch.findById(plan.seedBatchId).lean();
      cache[key] = sb?.cropType || sb?.crop || null;
    }
    if (cache[key]) return cache[key];
  }

  return plan.cropType || plan.crop || plan.variety || null;
}

/* -------------------- core compute (GDD) -------------------- */

/** Compute GDD for a plan between lastComputedAt (or startDate) and today */
async function computePlanGDD(plan) {
  // resolve crop name from seed batch first
  const cropName = await resolveCropName(plan);
  if (!cropName)
    return { updated: false, reason: "missing crop name (seed batch / plan)" };

  const crop = await Crop.findOne({ name: new RegExp(`^${cropName}$`, "i") });
  if (!crop)
    return { updated: false, reason: `missing crop baseline for ${cropName}` };

  const today = onlyDate(new Date());
  const start = onlyDate(new Date(plan.startDate));
  let state = await PhenologyState.findOne({ plan: plan._id });

  if (!state) {
    state = await PhenologyState.create({
      plan: plan._id,
      crop: cropName,
      section: plan.section,
      gddSum: 0,
      predictedStage: "none",
      lastComputedAt: null,
    });
  } else {
    // keep crop in sync with the seed batch
    if (state.crop !== cropName) {
      state.crop = cropName;
      await state.save();
    }
  }

  const from = state.lastComputedAt
    ? onlyDate(new Date(state.lastComputedAt))
    : start;
  if (from > today) return { updated: false, reason: "up to date" };

  // Pull daily climate rows for section between 'from' and 'today'
  const days = await ClimateDaily.find({
    section: plan.section,
    date: { $gte: from, $lte: today },
  }).sort({ date: 1 });

  let gddAdd = 0;
  for (const d of days) {
    const gdd = Math.max(0, meanTemp(d.tmin, d.tmax) - crop.baseTemp);
    gddAdd += gdd;
  }

  if (gddAdd === 0) {
    // no climate rows to integrate (keep waiting for data)
    return { updated: false, reason: "no climate rows" };
  }

  state.gddSum += gddAdd;
  state.lastComputedAt = today;

  // Predict stage by thresholds
  const T = crop.stageGDD || {};
  let nextStage = "none";
  if (state.gddSum >= (T.emergence ?? Infinity)) nextStage = "emergence";
  if (state.gddSum >= (T.vegetative ?? Infinity)) nextStage = "vegetative";
  if (state.gddSum >= (T.flowering ?? Infinity)) nextStage = "flowering";
  if (state.gddSum >= (T.fruiting ?? Infinity)) nextStage = "fruiting";

  const changed = nextStage !== state.predictedStage;
  state.predictedStage = nextStage;
  await state.save();

  // Autopilot: create tasks when crossing a stage threshold
  if (changed && nextStage !== "none") {
    const stageTasks = {
      emergence: ["Germination check", "Initial irrigation review"],
      vegetative: ["Trellising/Training", "Vegetative fertigation"],
      flowering: ["Pollination check", "Preventive fungicide (if needed)"],
      fruiting: ["Fruit thinning", "Harvest readiness scouting"],
    };
    const items = stageTasks[nextStage] || [];
    await Promise.all(
      items.map((title) =>
        Task.create({
          module: "growth",
          title: `${plan.section}: ${title}`,
          description: `Autogenerated by GDD at stage: ${nextStage}`,
          section: plan.section,
          priority: "medium",
          status: "todo",
          dueDate: new Date(), // now
        })
      )
    );
  }

  return {
    updated: true,
    gddAdd,
    newStage: state.predictedStage,
    gddSum: state.gddSum,
  };
}

/* ------------------------- endpoints ------------------------- */

/** GET /plant-cultivation/phenology/summary  -> per-plan snapshot */
exports.summary = async (req, res) => {
  try {
    const plans = await PlantingPlan.find({}).lean(); // or filter "active"
    const cropCache = {};
    const rows = await PhenologyState.find({
      plan: { $in: plans.map((p) => p._id) },
    }).lean();

    const map = new Map(rows.map((r) => [String(r.plan), r]));
    const data = await Promise.all(
      plans.map(async (p) => {
        const r = map.get(String(p._id));
        const cropName = await resolveCropName(p, cropCache);
        return {
          planId: p._id,
          crop: cropName || "—",
          section: p.section,
          startDate: p.startDate,
          gddSum: r?.gddSum ?? 0,
          predictedStage: r?.predictedStage ?? "none",
          lastComputedAt: r?.lastComputedAt || null,
        };
      })
    );

    res.json({ data, generatedAt: new Date() });
  } catch (e) {
    console.error(e);
    res.status(500).json({ message: "Failed to load phenology summary" });
  }
};

/** POST /plant-cultivation/phenology/recompute  -> recompute all plans now */
exports.recomputeAll = async (req, res) => {
  try {
    const plans = await PlantingPlan.find({});
    const out = [];
    for (const p of plans) {
      const r = await computePlanGDD(p);
      out.push({ plan: p._id, ...r });
    }
    res.json({ ok: true, results: out, at: new Date() });
  } catch (e) {
    console.error(e);
    res.status(500).json({ message: "Recompute failed" });
  }
};

/** GET /plant-cultivation/phenology/:planId  -> single plan phenology state */
exports.forPlan = async (req, res) => {
  try {
    const p = await PlantingPlan.findById(req.params.planId).lean();
    if (!p) return res.status(404).json({ message: "Plan not found" });

    const cropName = await resolveCropName(p);
    const r = await PhenologyState.findOne({ plan: p._id }).lean();

    res.json({
      data: r || {
        plan: p._id,
        crop: cropName || "—",
        section: p.section,
        gddSum: 0,
        predictedStage: "none",
      },
    });
  } catch (e) {
    console.error(e);
    res.status(500).json({ message: "Failed" });
  }
};

/* --------- Quick Climate Entry + Series for chart visual --------- */

/** POST /plant-cultivation/phenology/climate  (section, date, tmin, tmax) */
exports.addClimateDaily = async (req, res) => {
  try {
    const { section, date, tmin, tmax } = req.body || {};
    if (!section || !date)
      return res.status(400).json({ message: "section and date are required" });
    if (tmin == null || tmax == null)
      return res.status(400).json({ message: "tmin and tmax are required" });

    const day = new Date(date);
    day.setHours(0, 0, 0, 0);

    await ClimateDaily.updateOne(
      { section, date: day },
      { $set: { tmin: Number(tmin), tmax: Number(tmax) } },
      { upsert: true }
    );

    res.json({ ok: true });
  } catch (e) {
    console.error(e);
    res.status(500).json({ message: "Failed to save climate" });
  }
};

/** GET /plant-cultivation/phenology/series/:planId  -> GDD series for chart */
exports.seriesForPlan = async (req, res) => {
  try {
    const planId = req.params.planId;
    const plan = await PlantingPlan.findById(planId).lean();
    if (!plan) return res.status(404).json({ message: "Plan not found" });

    const cropName = await resolveCropName(plan);
    if (!cropName)
      return res
        .status(400)
        .json({ message: "No crop name (seed batch / plan)" });

    const crop = await Crop.findOne({
      name: new RegExp(`^${cropName}$`, "i"),
    }).lean();
    if (!crop)
      return res
        .status(400)
        .json({ message: `No crop baseline for ${cropName}` });

    const start = new Date(plan.startDate);
    start.setHours(0, 0, 0, 0);
    const today = new Date();
    today.setHours(0, 0, 0, 0);

    const rows = await ClimateDaily.find({
      section: plan.section,
      date: { $gte: start, $lte: today },
    })
      .sort({ date: 1 })
      .lean();

    let cum = 0;
    const data = rows.map((r) => {
      const mean = meanTemp(r.tmin, r.tmax);
      const gdd = Math.max(0, mean - crop.baseTemp);
      cum += gdd;
      return {
        date: r.date,
        tmin: r.tmin,
        tmax: r.tmax,
        mean: Number(mean.toFixed(1)),
        gdd: Number(gdd.toFixed(1)),
        cum: Number(cum.toFixed(1)),
      };
    });

    res.json({
      data,
      thresholds: crop.stageGDD,
      baseTemp: crop.baseTemp,
      meta: {
        planId: plan._id,
        crop: cropName,
        section: plan.section,
        startDate: plan.startDate,
      },
    });
  } catch (e) {
    console.error(e);
    res.status(500).json({ message: "Failed to build series" });
  }
};
