const Crop = require("../../Model/plantCultivation/CropModel");
const ClimateDaily = require("../../Model/plantCultivation/ClimateDailyModel");
const PhenologyState = require("../../Model/plantCultivation/PhenologyStateModel");
const PlantingPlan = require("../../Model/plantCultivation/PlantingPlanModel");
const Task = require("../../Model/plantCultivation/CultivationTaskModel");

const onlyDate = (d) => new Date(d.getFullYear(), d.getMonth(), d.getDate());
const meanTemp = (tmin, tmax) => (tmin + tmax) / 2;

/** Compute GDD for a plan between lastComputedAt (or startDate) and today */
async function computePlanGDD(plan) {
  const crop = await Crop.findOne({ name: new RegExp(`^${plan.crop}$`, "i") });
  if (!crop) return { updated: false, reason: "missing crop baseline" };

  const today = onlyDate(new Date());
  const start = onlyDate(new Date(plan.startDate));
  let state = await PhenologyState.findOne({ plan: plan._id });

  if (!state) {
    state = await PhenologyState.create({
      plan: plan._id,
      crop: plan.crop,
      section: plan.section,
      gddSum: 0,
      predictedStage: "none",
      lastComputedAt: null,
    });
  }

  const from = state.lastComputedAt
    ? onlyDate(new Date(state.lastComputedAt))
    : start;
  if (from > today) return { updated: false, reason: "up to date" };

  // Pull daily climate rows for section between 'from' and 'today'
  const days = await ClimateDaily.find({
    section: plan.section,
    date: { $gte: from, $lte: today },
  }).sort({ date: 1 });

  let gddAdd = 0;
  for (const d of days) {
    const gdd = Math.max(0, meanTemp(d.tmin, d.tmax) - crop.baseTemp);
    gddAdd += gdd;
  }

  if (gddAdd === 0) {
    // fallback: allow manual entry later; skip if no climate
    return { updated: false, reason: "no climate rows" };
  }

  state.gddSum += gddAdd;
  state.lastComputedAt = today;

  // Predict stage by thresholds
  const T = crop.stageGDD;
  let nextStage = "none";
  if (state.gddSum >= T.emergence) nextStage = "emergence";
  if (state.gddSum >= T.vegetative) nextStage = "vegetative";
  if (state.gddSum >= T.flowering) nextStage = "flowering";
  if (state.gddSum >= T.fruiting) nextStage = "fruiting";

  const changed = nextStage !== state.predictedStage;
  state.predictedStage = nextStage;
  await state.save();

  // Autopilot: create tasks when crossing a stage threshold
  if (changed && nextStage !== "none") {
    const stageTasks = {
      emergence: ["Germination check", "Initial irrigation review"],
      vegetative: ["Trellising/Training", "Vegetative fertigation"],
      flowering: ["Pollination check", "Preventive fungicide (if needed)"],
      fruiting: ["Fruit thinning", "Harvest readiness scouting"],
    };
    const items = stageTasks[nextStage] || [];
    await Promise.all(
      items.map((title) =>
        Task.create({
          module: "growth",
          title: `${plan.section}: ${title}`,
          description: `Autogenerated by GDD at stage: ${nextStage}`,
          section: plan.section,
          priority: "medium",
          status: "todo",
          dueDate: new Date(), // now
        })
      )
    );
  }

  return {
    updated: true,
    gddAdd,
    newStage: state.predictedStage,
    gddSum: state.gddSum,
  };
}

/** GET /plant-cultivation/phenology/summary  -> per-plan phenology snapshot */
exports.summary = async (req, res) => {
  try {
    const plans = await PlantingPlan.find({}); // could filter active-only
    const rows = await PhenologyState.find({
      plan: { $in: plans.map((p) => p._id) },
    });

    // pack with plan info
    const map = new Map(rows.map((r) => [String(r.plan), r]));
    const data = plans.map((p) => {
      const r = map.get(String(p._id));
      return {
        planId: p._id,
        crop: p.crop,
        section: p.section,
        startDate: p.startDate,
        gddSum: r?.gddSum ?? 0,
        predictedStage: r?.predictedStage ?? "none",
        lastComputedAt: r?.lastComputedAt || null,
      };
    });

    res.json({ data, generatedAt: new Date() });
  } catch (e) {
    console.error(e);
    res.status(500).json({ message: "Failed to load phenology summary" });
  }
};

/** POST /plant-cultivation/phenology/recompute  -> recompute all plans now */
exports.recomputeAll = async (req, res) => {
  try {
    const plans = await PlantingPlan.find({});
    const out = [];
    for (const p of plans) {
      const r = await computePlanGDD(p);
      out.push({ plan: p._id, ...r });
    }
    res.json({ ok: true, results: out, at: new Date() });
  } catch (e) {
    console.error(e);
    res.status(500).json({ message: "Recompute failed" });
  }
};

/** GET /plant-cultivation/phenology/:planId  -> single plan forecast */
exports.forPlan = async (req, res) => {
  try {
    const p = await PlantingPlan.findById(req.params.planId);
    if (!p) return res.status(404).json({ message: "Plan not found" });
    const r = await PhenologyState.findOne({ plan: p._id });
    res.json({
      data: r || {
        plan: p._id,
        crop: p.crop,
        section: p.section,
        gddSum: 0,
        predictedStage: "none",
      },
    });
  } catch (e) {
    console.error(e);
    res.status(500).json({ message: "Failed" });
  }
};
